name: Hello World
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: run_hello
              run: python hello.py
    build:
        runs-on: ubuntu-latest
        needs: [test]
        steps:
          - name: checkout
            uses: actions/checkout@v4
          - name: create_artifact
            uses: actions/create_artifact@v4
            with:
              name: hello_artifact
              path: .
