name: Workflow with artifacts
on: [push]
env:
  ARTIFACT_NAME: api_artifact
  PATH: .
jobs: 
    upload_artifact:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: upload_artifact
              uses: actions/upload-artifact@v2
              with:
                name: ${{ env.ARTIFACT_NAME }}
                path: ${{ env.PATH }}
            - name: print files and location
              run: |
                ls -l
                pwd