name: Workflow with artifacts
on: [push]
env:
  ARTIFACT_NAME: api_artifact
  PATH: .
jobs: 
    upload_artifact:
        runs-on: ubuntu-latest
        steps:
            - name: print files and location
              run: |
                pwd
            - name: checkout
              uses: actions/checkout@v4
              with: 
                ref: main
            - name: upload_artifact
              uses: actions/upload-artifact@v4
              with:
                name: ${{ env.ARTIFACT_NAME }}
                path: .
            - name: print files and location
              run: |
                  ls -l